package com.example.demo.model;

public enum ERole {
  ROLE_USER,
  ROLE_MODERATOR,
  ROLE_ADMIN,
  ROLE_RRHH_CONSULTANT,
  ROLE_RRHH_MANAGER,
  ROLE_RRHH_CONSULTANT_VACATION,
  ROLE_RRHH_CONSULTANT_VACATION_HISTORICAL,
  ROLE_RRHH_MANAGER_VACATION,
  ROLE_RRHH_MANAGER_VACATION_HISTORICAL,
  ROLE_RRHH_CONSULTANT_TIMETRACK,
  ROLE_RRHH_MANAGER_TIMETRACK

}
